Yuying branch
newtfire/newTutorials pull request #12
Opened 2022-02-11 00:44 UTC by Yuying-Jin

2022-02-15 00:56 UTC, arrowarchive commented
@Yuying-Jin It was interesting see how the code for this branch developed over several commits. One thing that caught my eye, however, was in the last commit. A lot of files in the final commit were "renamed without changes," which I have never seen before. I assume that this means that they were moved to another location in the repository.

If that's the case, it's good to know. From my own experience, renaming files in _GitHub_ has not worked out well for me and always ended in a merge conflict. I've found that the best way for me to rename a file, if I have to, is to copy the file outside of _GitHub,_ delete the original file, and renaming the duplicate outside the repository before cutting and pasting the duplicate in place of the original. Instead of renaming, I think _Git Bash_ recognizes it as deleting and adding a file.

2022-02-23 00:06 UTC, ebeshero requested changes
Suggestions: 
* Create just one perhaps small XML file for this to work. (maybe just work with one page of Kew Gardens).
* This will mean simplifying the XSLT a little as well. (You wouldn't be reading from a `collection()` for example.

* I am adding some small wording revisions as line-comments on the strokeDasharray.md file.

2022-02-23 00:06 UTC, ebeshero commented on SVG/stroke-dasharray/xml/KewG_p1-12.xml
> +
@Yuying-Jin Suggestion: Let's condense the XML into just one file, and simplify it so it's easy for someone to read if they are just interested in the tutorial.

2022-02-23 00:06 UTC, ebeshero commented on SVG/stroke-dasharray/strokeDasharray.md
>  *Stroke-dasharray* is an attribute to draw dotted lines with custom style. It can includes one or more values to define sizes of dashes and gaps.
Correction: It can include

2022-02-23 00:07 UTC, ebeshero commented on SVG/stroke-dasharray/strokeDasharray.md
>  Before solving this problem, we can try to imagine that if a stroke-dasharray attribute with two values has an infinite size of gaps, what would happen?
Instead of "infinite" change to "extremely large sized gap"

2022-02-23 00:08 UTC, ebeshero commented on SVG/stroke-dasharray/strokeDasharray.md
> -        <!-- 9999999 means an infinite value here. -->
In the comment: say "very high" instead of "infinite".

2022-02-23 00:10 UTC, ebeshero commented on SVG/stroke-dasharray/strokeDasharray.md
> +stroke-dasharray="2 \* pi \* r * *percent* , 2 \* pi \* r"
Put this in a code block so you don't have to use escape characters, like this:

```xml
stroke-dasharray="2 * pi * $r * $percent, 2 * pi * $r"
```

2022-02-23 00:12 UTC, ebeshero commented on SVG/stroke-dasharray/pieChart.xsl
> +    <xsl:variable name="KG" select="collection('xml/?select=*.xml')"/>
@Yuying-Jin If you're simplifying the XML to just one file for the purposes of this tutorial, you will not need the $KG `collection()` variable here (so you can just remove this line).

2022-02-23 00:13 UTC, ebeshero commented on SVG/stroke-dasharray/pieChart.xsl
> +    <xsl:variable name="total" select="$KG//page/*[not(self::line)][not(self::description)]! name() => count()"/>
@Yuying-Jin In the variables below, you would remove `$KG`.

2022-02-23 00:14 UTC, ebeshero commented on SVG/stroke-dasharray/pieChart.xsl
> +    <xsl:variable name="color" select="$KG//page/color => count()"/>
@Yuying-Jin For example, without the collection, you would be reading from the root element of the source document like this:

```xml
 <xsl:variable name="color" select="//page/color => count()"/>
```

2022-03-04 00:53 UTC, merged